import "../../static/JetBrainsMono-Regular.ttf";
import { UiState } from "../app-state.slint";
import { ListView } from "std-widgets.slint";
import { ChatHeader } from "./chat-header.slint";
import { ChatComposer } from "./chat-composer.slint";
import { MessageRow } from "./message-row.slint";

export component ChatMain inherits Rectangle {
    background: #000000;

    VerticalLayout {
        ChatHeader {}

        Rectangle {
            ListView {
                height: 100%;
                width: 100%;

                for msg[idx] in UiState.messages : MessageRow {
                    msg: msg;
                    is-first: idx == 0;
                }
            }
        }

        ChatComposer {}
    }
}
