export component ChatHeader inherits Rectangle {
    in-out property <string> active-room: "general";
    in-out property <bool> participants-visible: true;
    
    height: 64px;
    background: transparent;
    
    Rectangle {
        y: parent.height - 1px;
        x: 16px;
        width: parent.width - 32px;
        height: 1px;
        background: rgba(255, 255, 255, 0.18);
    }
    
    HorizontalLayout {
        padding-left: 24px;
        padding-right: 24px;
        alignment: space-between;
        
        HorizontalLayout {
            spacing: 12px;
            alignment: start;
            
            Image { source: @image-url("../../static/dropdown.svg"); width: 24px; height: 24px; colorize: rgba(255, 255, 255, 0.55); y: 20px;}
            VerticalLayout {
                alignment: center;
                Text { text: root.active-room; color: #FFFFFF; font-size: 18px; font-weight: 700; }
                Text { text: "matrix.org"; color: #40529F; font-size: 12px; }
            }
        }
        
        HorizontalLayout {
            spacing: 16px;
            alignment: center;
            
            Image { source: @image-url("../../static/pin.svg"); width: 24px; height: 24px; colorize: rgba(255, 255, 255, 0.55); y: 20px;}
            Rectangle {
                width: 24px; height: 24px; y: 20px;
                Image { source: @image-url("../../static/members.svg"); width: 24px; height: 24px; colorize: root.participants-visible ? #38BDF8 : rgba(255, 255, 255, 0.55); }
                TouchArea { clicked => { root.participants-visible = !root.participants-visible; } mouse-cursor: pointer; }
            }
        }
    }
}
