import "../../static/JetBrainsMono-Regular.ttf";
import { UiState } from "../app-state.slint";
import { ScrollView } from "std-widgets.slint";
import { ChatHeader } from "./chat-header.slint";
import { ChatComposer } from "./chat-composer.slint";
import { MessageRow } from "./message-row.slint";

export component ChatMain inherits Rectangle {
    background: #000000;

    auto-scroll-timer := Timer {
        interval: 50ms;
        running: false;
        triggered => {
            self.running = false;
            scroll-view.viewport-y = -100000px;
        }
    }

    VerticalLayout {
        ChatHeader {}

        Rectangle {
            scroll-view := ScrollView {
                height: 100%;
                width: 100%;
                viewport-width: self.width;

                VerticalLayout {
                    alignment: start;
                    for msg[idx] in UiState.messages : MessageRow {
                        msg: msg;
                        is-first: idx == 0;
                    }
                }
            }
        }

        ChatComposer {
            message-sent => {
                auto-scroll-timer.running = true;
            }
        }
    }
}
