name: 'build-test'

on:
 - pull_request
 - push

jobs:
  build-windows:
    runs-on: hetz
    container:
      image: git.flaxeneel2.net/streigen/build-environments/build-environment-windows:latest
    steps:
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
          chmod 400 ~/.ssh/config
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: "${{ secrets.SSH_KNOWN_HOSTS }}"
      - name: Build Windows
        run: cargo xwin build --target x86_64-pc-windows-msvc
        env:
          RUSTFLAGS: "-C link-arg=/FORCE:MULTIPLE -C link-arg=/ignore:4006 -C link-arg=/NODEFAULTLIB:libucrt.lib -C link-arg=/NODEFAULTLIB:libvcruntime.lib -C link-arg=/NODEFAULTLIB:libcmt.lib -C link-arg=ucrt.lib -C link-arg=vcruntime.lib"
  build-linux:
    runs-on: hetz
    container:
      image: git.flaxeneel2.net/streigen/build-environments/build-environment-linux:latest
    steps:
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
          chmod 400 ~/.ssh/config
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: "${{ secrets.SSH_KNOWN_HOSTS }}"
      - name: Build Linux
        run: cargo build
  build-android:
    runs-on: hetz
    container:
      image: git.flaxeneel2.net/streigen/build-environments/build-environment-android:latest
    steps:
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
          chmod 400 ~/.ssh/config
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: "${{ secrets.SSH_KNOWN_HOSTS }}"
      - name: Write android debug keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_DEBUG_KEYSTORE }}
        run: |
          mkdir -p ~/.android
          echo "$KEYSTORE_BASE64" | base64 -d > ~/.android/debug.keystore
          chmod 400 ~/.android/debug.keystore
      - name: Build Android
        run: bash scripts/android-build.sh

